using System.Runtime.CompilerServices;

namespace LibStored.Net.Generator.Tests;

public static  class ModuleInitializer
{
    [ModuleInitializer]
    public static void Init()
    {
        VerifySourceGenerators.Initialize();
        VerifierSettings.ScrubLines(line => line.Contains("// This file was generated by LibStored.Net v"));
    }
}
